print(bool(True))
print(bool(1))
print(bool(100))
print(bool('h'))
print(bool('hello'))
print(bool(2.6))
print(bool([1, 2, 3]))
print(bool((1, 2, 3)))
print(bool({'id': '123', 'name': 'Student 1'}))

print('-'*60)

print(bool(False))
print(bool(0))
print(bool(''))
print(bool([]))
print(bool(()))
print(bool({}))
